### ISSUE TITLE
关闭混淆,没问题,打开混淆就报错了

### ISSUE THREAD

**Issue by wu410830911** [liujingxing/rxhttp#308]
debug {
            // false- 打开混淆
            minifyEnabled true
            // false- 打开资源压缩
            shrinkResources true
            // 用于设置Proguard的路径；
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }

关闭混淆时,访问网络接口完全没问题

  debug {
            // true - 打开混淆
            minifyEnabled true
            // true - 打开资源压缩
            shrinkResources true
            // 用于设置Proguard的路径；
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
打开混淆,再访问

返回的接口参数我都看到了  code是200 data:后面的参数都看到了
  紧接着就进入到了
.onFailure {it:Throwable
            }
返回的异常信息是: 

```
 g.h.g.d:
    POST https://********************/*****/*******
    
    Code=0 message=null
    Server: nginx/1.16.0
    Date: Tue, 14 Sep 2021 07:21:15 GMT
    Content-Type: application/json; charset=utf-8
    Transfer-Encoding: chunked
    Connection: keep-alive
    Access-Control-Allow-Credentials: true
    Access-Control-Allow-Headers: Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since, X-Requested-With
    Access-Control-Allow-Methods: GET, POST, PATCH, PUT, DELETE
    Access-Control-Allow-Origin: *
    Access-Control-Allow-Origin: *
    Access-Control-Allow-Credentials: true
    Access-Control-Allow-Methods: GET, POST, OPTIONS
```
是什么原因啊?
